/**
 * The canonical subject taxonomy — the list that turns 135 schools' wording
 * into one question ("маркетинг").
 *
 * Two levels: a group, and the subjects inside it. `aliases` is the working
 * part. A Korean school writes 마케팅전공, 경영학과(마케팅), Department of
 * Marketing; the matcher strips 학과/학부/전공 and the like before comparing,
 * so an alias needs only the stem — `마케팅`, not `마케팅학과`.
 *
 * This file seeds the table (`pnpm study-fields:import`) and is never read at
 * runtime: once seeded, `StudyField` is admin-editable, and staff adding an
 * alias must not have it overwritten by the next import. The importer only
 * creates what is missing and adds aliases it does not already have.
 */

export interface StudyFieldSeed {
  slug: string;
  nameMn: string;
  nameEn: string;
  nameKo?: string;
  aliases?: string[];
  children?: StudyFieldSeed[];
}

export const STUDY_FIELD_TAXONOMY: StudyFieldSeed[] = [
  {
    slug: 'business',
    nameMn: 'Бизнес, эдийн засаг',
    nameEn: 'Business & Economics',
    nameKo: '경영·경제',
    aliases: ['경상', 'business', 'commerce'],
    children: [
      {
        slug: 'marketing',
        nameMn: 'Маркетинг',
        nameEn: 'Marketing',
        nameKo: '마케팅',
        aliases: ['marketing', 'маркетинг', '마케팅', '광고마케팅', '마케팅빅데이터'],
      },
      {
        slug: 'business-administration',
        nameMn: 'Бизнесийн удирдлага',
        nameEn: 'Business Administration',
        nameKo: '경영학',
        aliases: [
          '경영',
          '경영학',
          '기업경영',
          '글로벌경영',
          'business administration',
          'management',
          'бизнесийн удирдлага',
          'менежмент',
          'mba',
        ],
      },
      {
        slug: 'accounting',
        nameMn: 'Нягтлан бодох бүртгэл',
        nameEn: 'Accounting',
        nameKo: '회계학',
        aliases: ['회계', '세무', '회계세무', 'accounting', 'нягтлан', 'нягтлан бодох'],
      },
      {
        slug: 'finance',
        nameMn: 'Санхүү, банк',
        nameEn: 'Finance & Banking',
        nameKo: '재무·금융',
        aliases: ['금융', '재무', '보험', '핀테크', 'finance', 'banking', 'санхүү', 'банк'],
      },
      {
        slug: 'international-trade',
        nameMn: 'Олон улсын худалдаа',
        nameEn: 'International Trade',
        nameKo: '국제통상',
        aliases: [
          '무역',
          '국제통상',
          '통상',
          'international trade',
          'олон улсын худалдаа',
          'гадаад худалдаа',
        ],
      },
      {
        slug: 'economics',
        nameMn: 'Эдийн засаг',
        nameEn: 'Economics',
        nameKo: '경제학',
        aliases: ['경제', 'economics', 'эдийн засаг'],
      },
      {
        slug: 'logistics',
        nameMn: 'Логистик, ханган нийлүүлэлт',
        nameEn: 'Logistics & Supply Chain',
        nameKo: '물류',
        aliases: ['물류', '유통', '해운', 'logistics', 'supply chain', 'логистик'],
      },
      {
        slug: 'management-information-systems',
        nameMn: 'Бизнесийн мэдээллийн систем',
        nameEn: 'Management Information Systems',
        nameKo: '경영정보',
        aliases: ['경영정보', 'mis', 'e비즈니스', 'business analytics'],
      },
    ],
  },
  {
    slug: 'it',
    nameMn: 'Мэдээллийн технологи',
    nameEn: 'Information Technology',
    nameKo: 'IT·컴퓨터',
    aliases: ['it', '정보기술'],
    children: [
      {
        slug: 'computer-science',
        nameMn: 'Компьютерийн ухаан, программ хангамж',
        nameEn: 'Computer Science & Software',
        nameKo: '컴퓨터공학',
        aliases: [
          '컴퓨터',
          '컴퓨터공학',
          '소프트웨어',
          '전산',
          '컴퓨터과학',
          'computer science',
          'software',
          'программ хангамж',
          'компьютер',
        ],
      },
      {
        slug: 'artificial-intelligence',
        nameMn: 'Хиймэл оюун',
        nameEn: 'Artificial Intelligence',
        nameKo: '인공지능',
        aliases: ['인공지능', 'ai', 'artificial intelligence', 'machine learning', 'хиймэл оюун'],
      },
      {
        slug: 'data-science',
        nameMn: 'Өгөгдлийн шинжлэх ухаан',
        nameEn: 'Data Science',
        nameKo: '데이터사이언스',
        aliases: ['데이터', '빅데이터', 'data science', 'big data', 'өгөгдөл', 'дата'],
      },
      {
        slug: 'information-security',
        nameMn: 'Мэдээллийн аюулгүй байдал',
        nameEn: 'Information Security',
        nameKo: '정보보호',
        aliases: ['정보보호', '정보보안', '사이버보안', 'cyber security', 'кибер аюулгүй'],
      },
      {
        slug: 'game-development',
        nameMn: 'Тоглоом хөгжүүлэлт',
        nameEn: 'Game Development',
        nameKo: '게임',
        aliases: ['게임', 'game', 'тоглоом'],
      },
      {
        slug: 'information-communication',
        nameMn: 'Мэдээлэл холбоо',
        nameEn: 'Information & Communication Engineering',
        nameKo: '정보통신',
        aliases: ['정보통신', '통신공학', 'ict', 'telecommunication'],
      },
    ],
  },
  {
    slug: 'engineering',
    nameMn: 'Инженер, технологи',
    nameEn: 'Engineering',
    nameKo: '공학',
    aliases: ['공과', '공학', 'engineering', 'инженер'],
    children: [
      {
        slug: 'mechanical-engineering',
        nameMn: 'Механик инженер',
        nameEn: 'Mechanical Engineering',
        nameKo: '기계공학',
        aliases: ['기계', '기계공학', 'mechanical', 'механик'],
      },
      {
        slug: 'electrical-electronic-engineering',
        nameMn: 'Цахилгаан, электроник',
        nameEn: 'Electrical & Electronic Engineering',
        nameKo: '전기전자공학',
        aliases: [
          '전기',
          '전자',
          '전기전자',
          '반도체',
          'electrical',
          'electronic',
          'цахилгаан',
          'электроник',
        ],
      },
      {
        slug: 'civil-engineering',
        nameMn: 'Барилга, иргэний инженер',
        nameEn: 'Civil Engineering',
        nameKo: '토목공학',
        aliases: ['토목', '건설', '도시공학', 'civil engineering', 'барилга'],
      },
      {
        slug: 'architecture',
        nameMn: 'Архитектур',
        nameEn: 'Architecture',
        nameKo: '건축학',
        aliases: ['건축', 'architecture', 'архитектур'],
      },
      {
        slug: 'chemical-engineering',
        nameMn: 'Хими, технологийн инженер',
        nameEn: 'Chemical Engineering',
        nameKo: '화학공학',
        aliases: ['화공', '화학공학', 'chemical engineering'],
      },
      {
        slug: 'materials-engineering',
        nameMn: 'Материал судлал',
        nameEn: 'Materials Science',
        nameKo: '신소재공학',
        aliases: ['신소재', '재료공학', '금속', 'materials'],
      },
      {
        slug: 'industrial-engineering',
        nameMn: 'Үйлдвэрлэлийн инженер',
        nameEn: 'Industrial Engineering',
        nameKo: '산업공학',
        aliases: ['산업공학', '산업경영공학', 'industrial engineering'],
      },
      {
        slug: 'automotive-engineering',
        nameMn: 'Автомашины инженер',
        nameEn: 'Automotive Engineering',
        nameKo: '자동차공학',
        aliases: ['자동차', 'automotive', 'автомашин'],
      },
      {
        slug: 'aerospace-engineering',
        nameMn: 'Нисэх, сансрын инженер',
        nameEn: 'Aerospace Engineering',
        nameKo: '항공우주공학',
        aliases: ['항공우주', '항공공학', 'aerospace', 'нисэх'],
      },
      {
        slug: 'environmental-engineering',
        nameMn: 'Байгаль орчны инженер',
        nameEn: 'Environmental Engineering',
        nameKo: '환경공학',
        aliases: ['환경', '환경공학', 'environmental', 'байгаль орчин'],
      },
      {
        slug: 'energy-engineering',
        nameMn: 'Эрчим хүч',
        nameEn: 'Energy Engineering',
        nameKo: '에너지공학',
        aliases: ['에너지', '원자력', 'energy', 'эрчим хүч'],
      },
      {
        slug: 'robotics-mechatronics',
        nameMn: 'Робот техник, мехатроник',
        nameEn: 'Robotics & Mechatronics',
        nameKo: '로봇공학',
        aliases: ['로봇', '메카트로닉스', 'robotics', 'mechatronics', 'робот'],
      },
    ],
  },
  {
    slug: 'natural-science',
    nameMn: 'Байгалийн ухаан',
    nameEn: 'Natural Sciences',
    nameKo: '자연과학',
    aliases: ['자연과학', '이과', 'natural science'],
    children: [
      {
        slug: 'mathematics',
        nameMn: 'Математик',
        nameEn: 'Mathematics',
        nameKo: '수학',
        aliases: ['수학', 'mathematics', 'математик'],
      },
      {
        slug: 'physics',
        nameMn: 'Физик',
        nameEn: 'Physics',
        nameKo: '물리학',
        aliases: ['물리', 'physics', 'физик'],
      },
      {
        slug: 'chemistry',
        nameMn: 'Хими',
        nameEn: 'Chemistry',
        nameKo: '화학',
        aliases: ['화학과', 'chemistry', 'хими'],
      },
      {
        slug: 'biology',
        nameMn: 'Биологи, амьдралын шинжлэх ухаан',
        nameEn: 'Biology & Life Sciences',
        nameKo: '생명과학',
        aliases: ['생명', '생물', '생명공학', 'biology', 'life science', 'биологи'],
      },
      {
        slug: 'statistics',
        nameMn: 'Статистик',
        nameEn: 'Statistics',
        nameKo: '통계학',
        aliases: ['통계', 'statistics', 'статистик'],
      },
    ],
  },
  {
    slug: 'medical',
    nameMn: 'Анагаах ухаан, эрүүл мэнд',
    nameEn: 'Medicine & Health',
    nameKo: '의약·보건',
    aliases: ['의료', '보건', 'medical', 'health'],
    children: [
      {
        slug: 'medicine',
        nameMn: 'Хүн эмнэлэг',
        nameEn: 'Medicine',
        nameKo: '의학',
        aliases: ['의예', '의학', 'medicine', 'анагаах'],
      },
      {
        slug: 'dentistry',
        nameMn: 'Шүдний эмнэлэг',
        nameEn: 'Dentistry',
        nameKo: '치의학',
        aliases: ['치의학', '치예', 'dentistry', 'шүд'],
      },
      {
        slug: 'oriental-medicine',
        nameMn: 'Дорнын анагаах ухаан',
        nameEn: 'Korean Oriental Medicine',
        nameKo: '한의학',
        aliases: ['한의학', '한의예', 'oriental medicine'],
      },
      {
        slug: 'pharmacy',
        nameMn: 'Эм зүй',
        nameEn: 'Pharmacy',
        nameKo: '약학',
        aliases: ['약학', 'pharmacy', 'эм зүй'],
      },
      {
        slug: 'nursing',
        nameMn: 'Сувилахуй',
        nameEn: 'Nursing',
        nameKo: '간호학',
        aliases: ['간호', 'nursing', 'сувилахуй'],
      },
      {
        slug: 'physical-therapy',
        nameMn: 'Сэргээн засах эмчилгээ',
        nameEn: 'Physical Therapy',
        nameKo: '물리치료',
        aliases: ['물리치료', '작업치료', '재활', 'physical therapy'],
      },
      {
        slug: 'public-health',
        nameMn: 'Нийтийн эрүүл мэнд, эмнэлгийн удирдлага',
        nameEn: 'Public Health & Healthcare Management',
        nameKo: '보건행정',
        aliases: ['보건행정', '의료경영', '보건학', 'public health'],
      },
      {
        slug: 'beauty-care',
        nameMn: 'Гоо сайхан',
        nameEn: 'Beauty & Cosmetology',
        nameKo: '뷰티',
        aliases: ['뷰티', '미용', '화장품', 'beauty', 'cosmetology', 'гоо сайхан'],
      },
    ],
  },
  {
    slug: 'social-science',
    nameMn: 'Нийгмийн ухаан',
    nameEn: 'Social Sciences',
    nameKo: '사회과학',
    aliases: ['사회과학', 'social science'],
    children: [
      {
        slug: 'public-administration',
        nameMn: 'Төрийн удирдлага',
        nameEn: 'Public Administration',
        nameKo: '행정학',
        aliases: ['행정', 'public administration', 'төрийн удирдлага'],
      },
      {
        slug: 'political-science',
        nameMn: 'Улс төр, олон улс судлал',
        nameEn: 'Political Science & International Relations',
        nameKo: '정치외교',
        aliases: ['정치', '외교', '국제관계', '국제학', 'political science', 'улс төр', 'олон улс'],
      },
      {
        slug: 'sociology',
        nameMn: 'Социологи',
        nameEn: 'Sociology',
        nameKo: '사회학',
        aliases: ['사회학', 'sociology', 'социологи'],
      },
      {
        slug: 'psychology',
        nameMn: 'Сэтгэл судлал',
        nameEn: 'Psychology',
        nameKo: '심리학',
        aliases: ['심리', 'psychology', 'сэтгэл судлал'],
      },
      {
        slug: 'social-welfare',
        nameMn: 'Нийгмийн халамж',
        nameEn: 'Social Welfare',
        nameKo: '사회복지',
        aliases: ['사회복지', 'social welfare', 'нийгмийн ажил'],
      },
      {
        slug: 'police-administration',
        nameMn: 'Цагдаагийн удирдлага',
        nameEn: 'Police Administration',
        nameKo: '경찰행정',
        aliases: ['경찰', '경호', 'police', 'security administration'],
      },
      {
        slug: 'real-estate',
        nameMn: 'Үл хөдлөх хөрөнгө',
        nameEn: 'Real Estate',
        nameKo: '부동산학',
        aliases: ['부동산', 'real estate'],
      },
      {
        slug: 'law',
        nameMn: 'Хууль зүй',
        nameEn: 'Law',
        nameKo: '법학',
        aliases: ['법학', '법과', 'law', 'хууль'],
      },
    ],
  },
  {
    slug: 'humanities',
    nameMn: 'Хүмүүнлэг, хэл шинжлэл',
    nameEn: 'Humanities & Languages',
    nameKo: '인문·어학',
    aliases: ['인문', '어문', 'humanities'],
    children: [
      {
        slug: 'korean-language-literature',
        nameMn: 'Солонгос хэл, уран зохиол',
        nameEn: 'Korean Language & Literature',
        nameKo: '국어국문학',
        aliases: ['국어국문', '국문', 'korean literature', 'солонгос хэл'],
      },
      {
        slug: 'english-language-literature',
        nameMn: 'Англи хэл, уран зохиол',
        nameEn: 'English Language & Literature',
        nameKo: '영어영문학',
        aliases: ['영어영문', '영문', 'english literature', 'англи хэл'],
      },
      {
        slug: 'chinese-studies',
        nameMn: 'Хятад судлал',
        nameEn: 'Chinese Studies',
        nameKo: '중어중문학',
        aliases: ['중어중문', '중국학', 'chinese studies'],
      },
      {
        slug: 'japanese-studies',
        nameMn: 'Япон судлал',
        nameEn: 'Japanese Studies',
        nameKo: '일어일문학',
        aliases: ['일어일문', '일본학', 'japanese studies'],
      },
      {
        slug: 'history',
        nameMn: 'Түүх',
        nameEn: 'History',
        nameKo: '사학',
        aliases: ['사학', '역사', 'history', 'түүх'],
      },
      {
        slug: 'philosophy',
        nameMn: 'Гүн ухаан',
        nameEn: 'Philosophy',
        nameKo: '철학',
        aliases: ['철학', 'philosophy', 'гүн ухаан'],
      },
      {
        slug: 'korean-studies',
        nameMn: 'Солонгос судлал',
        nameEn: 'Korean Studies',
        nameKo: '한국학',
        aliases: ['한국학', '한국문화', 'korean studies'],
      },
    ],
  },
  {
    slug: 'education',
    nameMn: 'Боловсрол, багш',
    nameEn: 'Education',
    nameKo: '사범·교육',
    aliases: ['사범', '교육', 'education', 'багш'],
    children: [
      {
        slug: 'early-childhood-education',
        nameMn: 'Сургуулийн өмнөх боловсрол',
        nameEn: 'Early Childhood Education',
        nameKo: '유아교육',
        aliases: ['유아교육', '아동', 'early childhood', 'цэцэрлэг'],
      },
      {
        slug: 'elementary-education',
        nameMn: 'Бага ангийн боловсрол',
        nameEn: 'Elementary Education',
        nameKo: '초등교육',
        aliases: ['초등교육', 'elementary education'],
      },
      {
        slug: 'korean-language-education',
        nameMn: 'Солонгос хэлний багш',
        nameEn: 'Korean Language Education',
        nameKo: '한국어교육',
        aliases: ['한국어교육', '외국어로서의한국어', 'korean language education'],
      },
      {
        slug: 'physical-education',
        nameMn: 'Биеийн тамирын багш',
        nameEn: 'Physical Education',
        nameKo: '체육교육',
        aliases: ['체육교육', 'physical education'],
      },
      {
        slug: 'special-education',
        nameMn: 'Тусгай боловсрол',
        nameEn: 'Special Education',
        nameKo: '특수교육',
        aliases: ['특수교육', 'special education'],
      },
    ],
  },
  {
    slug: 'arts-design',
    nameMn: 'Урлаг, дизайн',
    nameEn: 'Arts & Design',
    nameKo: '예술·디자인',
    aliases: ['예술', '예체능', 'arts'],
    children: [
      {
        slug: 'design',
        nameMn: 'Дизайн',
        nameEn: 'Design',
        nameKo: '디자인',
        aliases: ['디자인', '시각디자인', '산업디자인', 'design', 'дизайн'],
      },
      {
        slug: 'fashion-design',
        nameMn: 'Загвар зохион бүтээх',
        nameEn: 'Fashion Design',
        nameKo: '패션디자인',
        aliases: ['패션', '의상', 'fashion', 'загвар'],
      },
      {
        slug: 'interior-design',
        nameMn: 'Дотоод засал, орчны дизайн',
        nameEn: 'Interior & Environmental Design',
        nameKo: '실내디자인',
        aliases: ['실내디자인', '실내건축', '환경디자인', 'interior design'],
      },
      {
        slug: 'music',
        nameMn: 'Хөгжим',
        nameEn: 'Music',
        nameKo: '음악',
        aliases: ['음악', '실용음악', 'music', 'хөгжим'],
      },
      {
        slug: 'fine-art',
        nameMn: 'Дүрслэх урлаг',
        nameEn: 'Fine Art',
        nameKo: '미술',
        aliases: ['미술', '회화', '조소', 'fine art', 'дүрслэх урлаг'],
      },
      {
        slug: 'performing-arts',
        nameMn: 'Театр, кино урлаг',
        nameEn: 'Theatre & Film',
        nameKo: '연극영화',
        aliases: ['연극', '영화', '연기', 'film', 'theatre', 'кино'],
      },
      {
        slug: 'animation',
        nameMn: 'Анимэйшн, цуврал зураг',
        nameEn: 'Animation & Comics',
        nameKo: '애니메이션',
        aliases: ['애니메이션', '만화', 'animation', 'анимэйшн'],
      },
      {
        slug: 'photography',
        nameMn: 'Гэрэл зураг',
        nameEn: 'Photography',
        nameKo: '사진',
        aliases: ['사진', 'photography'],
      },
    ],
  },
  {
    slug: 'media-communication',
    nameMn: 'Хэвлэл мэдээлэл, харилцаа холбоо',
    nameEn: 'Media & Communication',
    nameKo: '미디어·커뮤니케이션',
    aliases: ['미디어', '커뮤니케이션', 'media'],
    children: [
      {
        slug: 'journalism-media',
        nameMn: 'Сэтгүүл зүй, медиа',
        nameEn: 'Journalism & Media Studies',
        nameKo: '신문방송학',
        aliases: ['신문방송', '언론', '미디어커뮤니케이션', 'journalism', 'сэтгүүл зүй'],
      },
      {
        slug: 'advertising-pr',
        nameMn: 'Сурталчилгаа, олон нийттэй харилцах',
        nameEn: 'Advertising & Public Relations',
        nameKo: '광고홍보학',
        aliases: ['광고홍보', '광고', '홍보', 'advertising', 'public relations', 'pr'],
      },
      {
        slug: 'content-production',
        nameMn: 'Контент бүтээл',
        nameEn: 'Content Production',
        nameKo: '콘텐츠',
        aliases: ['콘텐츠', '방송영상', '영상제작', 'content', 'контент'],
      },
    ],
  },
  {
    slug: 'tourism-service',
    nameMn: 'Аялал жуулчлал, үйлчилгээ',
    nameEn: 'Tourism & Service',
    nameKo: '관광·서비스',
    aliases: ['관광', '서비스', 'tourism'],
    children: [
      {
        slug: 'tourism-management',
        nameMn: 'Аялал жуулчлалын менежмент',
        nameEn: 'Tourism Management',
        nameKo: '관광경영',
        aliases: ['관광', '관광경영', 'tourism', 'аялал жуулчлал'],
      },
      {
        slug: 'hotel-management',
        nameMn: 'Зочид буудлын менежмент',
        nameEn: 'Hotel Management',
        nameKo: '호텔경영',
        aliases: ['호텔', '호텔경영', 'hotel management', 'зочид буудал'],
      },
      {
        slug: 'culinary-food-service',
        nameMn: 'Тогооч, хоолны үйлчилгээ',
        nameEn: 'Culinary Arts & Food Service',
        nameKo: '조리·외식',
        aliases: ['조리', '외식', '제과제빵', 'culinary', 'тогооч', 'нарийн боов'],
      },
      {
        slug: 'airline-service',
        nameMn: 'Агаарын тээврийн үйлчилгээ',
        nameEn: 'Airline Service',
        nameKo: '항공서비스',
        aliases: ['항공서비스', '승무원', 'airline service', 'нисэхийн үйлчилгээ'],
      },
      {
        slug: 'sports-leisure',
        nameMn: 'Спорт, чөлөөт цаг',
        nameEn: 'Sports & Leisure',
        nameKo: '스포츠레저',
        aliases: ['스포츠', '체육', '레저', 'sports', 'спорт'],
      },
    ],
  },
  {
    slug: 'agriculture-food',
    nameMn: 'Хөдөө аж ахуй, хүнс',
    nameEn: 'Agriculture & Food',
    nameKo: '농생명·식품',
    aliases: ['농업', '농생명', 'agriculture'],
    children: [
      {
        slug: 'food-science-nutrition',
        nameMn: 'Хүнсний технологи, хоол тэжээл',
        nameEn: 'Food Science & Nutrition',
        nameKo: '식품영양학',
        aliases: ['식품', '식품영양', '식품공학', 'food science', 'nutrition', 'хүнс'],
      },
      {
        slug: 'agriculture-science',
        nameMn: 'Газар тариалан, мал аж ахуй',
        nameEn: 'Agricultural Science',
        nameKo: '농학',
        aliases: ['농학', '원예', '축산', 'agriculture', 'хөдөө аж ахуй'],
      },
      {
        slug: 'veterinary-medicine',
        nameMn: 'Мал эмнэлэг',
        nameEn: 'Veterinary Medicine',
        nameKo: '수의학',
        aliases: ['수의학', '수의예', 'veterinary', 'мал эмнэлэг'],
      },
    ],
  },
  {
    // A group of one, on purpose: a language course is not a degree subject,
    // but it is what a large share of clients come for, and the filter panel
    // needs somewhere to put it.
    slug: 'language-training',
    nameMn: 'Хэлний бэлтгэл',
    nameEn: 'Language Training',
    nameKo: '어학연수',
    children: [
      {
        slug: 'korean-language-program',
        nameMn: 'Солонгос хэлний бэлтгэл',
        nameEn: 'Korean Language Program',
        nameKo: '한국어 어학연수',
        aliases: [
          '어학당',
          '한국어학당',
          // Longer than `한국어교육`, so a language institute is not read as the
          // teaching degree next door in `korean-language-education`.
          '한국어교육원',
          '한국어연수',
          '어학연수',
          'korean language institute',
          'language program',
          'хэлний бэлтгэл',
          'хэлний сургалт',
        ],
      },
    ],
  },
];

/** Every seed row flattened, groups first. */
export function flattenTaxonomy(seeds: StudyFieldSeed[] = STUDY_FIELD_TAXONOMY): StudyFieldSeed[] {
  return seeds.flatMap((seed) => [seed, ...flattenTaxonomy(seed.children ?? [])]);
}
