#!/usr/bin/env bash
# Generates deploy/.env.production — the production environment, kept on the
# deploying machine and copied to the server by deploy.sh.
#
# Safe to re-run: an existing file is never overwritten. Delete it deliberately
# if you want fresh secrets (rotating JWT_SECRET logs every user out; rotating
# DB_PASSWORD needs ./deploy/database.sh afterwards).

source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

ENV_FILE="$DEPLOY_DIR/.env.production"

if [[ -f "$ENV_FILE" ]]; then
  warn "deploy/.env.production already exists — leaving it alone"
  exit 0
fi

secret() { openssl rand -base64 48 | tr -d '\n/+=' | head -c 48; }
# Postgres passwords travel through psql and a URL, so keep them alphanumeric.
pgpass() { openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 28; }

DB_PASSWORD="$(pgpass)"

cat > "$ENV_FILE" <<EOF
# =========================================================
#  GKSedu.mn — production environment
#  Generated by deploy/init-env.sh. Not in git. Copied to
#  $REMOTE_ENV by deploy/deploy.sh.
# =========================================================

# Password for the '$DB_USER' role. deploy/database.sh applies it.
DB_PASSWORD=$DB_PASSWORD

# --- Database ---------------------------------------------------------------
# Postgres 17 runs on the server itself and listens on localhost only, so there
# is no pooler in front of it: DATABASE_URL and DIRECT_URL are the same.
DATABASE_URL="postgresql://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME?schema=public&connection_limit=10"
DIRECT_URL="postgresql://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME?schema=public"

# --- Redis ------------------------------------------------------------------
REDIS_URL="redis://127.0.0.1:6379/0"

# --- API --------------------------------------------------------------------
NODE_ENV=production
API_PORT=$API_PORT
# Nitro's listen port for the Nuxt server; read by deploy/ecosystem.config.cjs.
WEB_PORT=$WEB_PORT
API_PREFIX=api
CORS_ORIGIN=https://$DOMAIN,https://$WWW_DOMAIN

JWT_SECRET=$(secret)
JWT_EXPIRES_IN=15m
JWT_REFRESH_SECRET=$(secret)
JWT_REFRESH_EXPIRES_IN=7d

EMBEDDING_DIMENSIONS=1536

# --- QPay -------------------------------------------------------------------
# No merchant account yet, so invoices are faked. Flip QPAY_MOCK to false and
# fill the four credentials in once GKS EDU has a QPay merchant.
QPAY_MOCK=true
QPAY_BASE_URL="https://merchant.qpay.mn/v2"
QPAY_USERNAME=
QPAY_PASSWORD=
QPAY_INVOICE_CODE=
QPAY_CALLBACK_URL="https://$DOMAIN/api/v1/payments/qpay/webhook"

# --- Google sign-in ---------------------------------------------------------
# Unset = the "Google-ээр нэвтрэх" button does not render and POST /auth/google
# returns 503. Both variables must hold the same OAuth 2.0 Web client id, and
# https://$DOMAIN must be an authorised JavaScript origin on it.
# GOOGLE_CLIENT_ID=
# NUXT_PUBLIC_GOOGLE_CLIENT_ID=

# --- Notifications ----------------------------------------------------------
# With RESEND_API_KEY unset the API logs each email instead of sending it.
# RESEND_API_KEY=
NOTIFICATION_FROM_EMAIL="GKSedu <noreply@$DOMAIN>"
# NOTIFICATION_STAFF_EMAIL=
APP_PUBLIC_URL=https://$DOMAIN
SMS_DAILY_LIMIT_PER_USER=3
SMS_DAILY_LIMIT_GLOBAL=500

# --- Storage ----------------------------------------------------------------
# Uploaded documents live on the server's disk, outside the deployed code so
# that a deploy's rsync --delete can never remove them.
STORAGE_DRIVER=local
STORAGE_LOCAL_DIR=$STORAGE_DIR
STORAGE_SIGNING_SECRET=$(secret)

# --- Web --------------------------------------------------------------------
NUXT_PUBLIC_API_BASE=https://$DOMAIN/api/v1
NUXT_PUBLIC_SITE_URL=https://$DOMAIN
# NUXT_PUBLIC_GA_ID=
EOF

chmod 600 "$ENV_FILE"
ok "Wrote deploy/.env.production (gitignored)"
warn "Keep a copy somewhere safe — it holds the only copy of the production secrets."
