#!/usr/bin/env bash
# Generates deploy/.env.production — the production environment, kept on the
# deploying machine and copied to the server by deploy.sh.
#
# Safe to re-run: an existing file is never overwritten. Delete it deliberately
# if you want fresh secrets (rotating JWT_SECRET logs every user out; rotating
# DB_PASSWORD needs ./deploy/database.sh afterwards).

source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

ENV_FILE="$DEPLOY_DIR/.env.production"

if [[ -f "$ENV_FILE" ]]; then
  warn "deploy/.env.production already exists — leaving it alone"
  exit 0
fi

secret() { openssl rand -base64 48 | tr -d '\n/+=' | head -c 48; }
# Postgres passwords travel through psql and a URL, so keep them alphanumeric.
pgpass() { openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 28; }

DB_PASSWORD="$(pgpass)"

cat > "$ENV_FILE" <<EOF
# =========================================================
#  GKSedu.mn — production environment
#  Generated by deploy/init-env.sh. Not in git. Copied to
#  $REMOTE_ENV by deploy/deploy.sh.
# =========================================================

# Password for the '$DB_USER' role. deploy/database.sh applies it.
DB_PASSWORD=$DB_PASSWORD

# --- Database ---------------------------------------------------------------
# Postgres 17 runs on the server itself and listens on localhost only, so there
# is no pooler in front of it: DATABASE_URL and DIRECT_URL are the same.
DATABASE_URL="postgresql://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME?schema=public&connection_limit=10"
DIRECT_URL="postgresql://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME?schema=public"

# --- Redis ------------------------------------------------------------------
REDIS_URL="redis://127.0.0.1:6379/0"

# --- API --------------------------------------------------------------------
NODE_ENV=production
API_PORT=$API_PORT
# Nitro's listen port for the Nuxt server; read by deploy/ecosystem.config.cjs.
WEB_PORT=$WEB_PORT
API_PREFIX=api
CORS_ORIGIN=https://$DOMAIN,https://$WWW_DOMAIN

JWT_SECRET=$(secret)
JWT_EXPIRES_IN=15m
JWT_REFRESH_SECRET=$(secret)
JWT_REFRESH_EXPIRES_IN=7d

EMBEDDING_DIMENSIONS=1536

# --- QPay -------------------------------------------------------------------
# No merchant account yet, so invoices are faked. Flip QPAY_MOCK to false and
# fill the four credentials in once GKS EDU has a QPay merchant.
QPAY_MOCK=true
QPAY_BASE_URL="https://merchant.qpay.mn/v2"
QPAY_USERNAME=
QPAY_PASSWORD=
QPAY_INVOICE_CODE=
QPAY_CALLBACK_URL="https://$DOMAIN/api/v1/payments/qpay/webhook"

# --- Google sign-in ---------------------------------------------------------
# Unset = the "Google-ээр нэвтрэх" button does not render and POST /auth/google
# returns 503. Both variables must hold the same OAuth 2.0 Web client id, and
# https://$DOMAIN must be an authorised JavaScript origin on it.
# GOOGLE_CLIENT_ID=
# NUXT_PUBLIC_GOOGLE_CLIENT_ID=

# --- Notifications ----------------------------------------------------------
# Resend. The from-address's domain must be a verified sending domain on the
# account; without the key the API logs each email instead of sending it.
# RESEND_API_KEY=
NOTIFICATION_FROM_EMAIL="GKSedu <noreply@$DOMAIN>"
# NOTIFICATION_STAFF_EMAIL=
APP_PUBLIC_URL=https://$DOMAIN
SMS_DAILY_LIMIT_PER_USER=3
SMS_DAILY_LIMIT_GLOBAL=500

# --- Slack (staff channel) --------------------------------------------------
# Bot token (`xoxb-…`) with `chat:write`, and the channel the office watches.
# The bot must be invited to the channel or Slack answers `not_in_channel`.
# Unset either one and the API logs the message instead of posting.
SLACK_BOT_TOKEN=
SLACK_CHANNEL_ID=

# --- Gemini (1H-10) ----------------------------------------------------------
# The admin "research this school's intake calendar online" button. With no key
# GEMINI_MOCK stays true and the screen gets a labelled fixture instead, so the
# feature is usable before the key exists — the same arrangement as QPAY_MOCK.
GEMINI_API_KEY=
GEMINI_MODEL="gemini-3.1-flash-lite"
GEMINI_TIMEOUT_MS=120000
GEMINI_MOCK=true

# --- Storage ----------------------------------------------------------------
# Uploaded documents live on the server's disk, outside the deployed code so
# that a deploy's rsync --delete can never remove them.
STORAGE_DRIVER=local
STORAGE_LOCAL_DIR=$STORAGE_DIR
STORAGE_SIGNING_SECRET=$(secret)

# --- Meta pixel + Conversions API (1A-38) -----------------------------------
# One dataset written to from two sides. META_PIXEL_ID and
# NUXT_PUBLIC_META_PIXEL_ID must hold the same value or the browser and the
# server land in different datasets and nothing deduplicates. The token is a
# system-user token from Events Manager -> Settings; the dataset id is public.
# Unset either the id or the token and the API logs instead of sending, and the
# web app injects no pixel script at all.
META_PIXEL_ID=1858714955098486
META_CAPI_ACCESS_TOKEN=
# Set while checking the setup in Events Manager -> Test events, then clear it:
# an event carrying a code is excluded from measurement.
# META_TEST_EVENT_CODE=

# --- Web --------------------------------------------------------------------
NUXT_PUBLIC_API_BASE=https://$DOMAIN/api/v1
NUXT_PUBLIC_SITE_URL=https://$DOMAIN
# GA4 property for gksedu.mn.
NUXT_PUBLIC_GA_ID=G-CZ24PGBE0Q
# Same value as META_PIXEL_ID above — it is public by design.
NUXT_PUBLIC_META_PIXEL_ID=1858714955098486
EOF

chmod 600 "$ENV_FILE"
ok "Wrote deploy/.env.production (gitignored)"
warn "Keep a copy somewhere safe — it holds the only copy of the production secrets."
